services:
  postgres:
    image: postgres:17.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:9.0
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    networks:
      - backend
    ports:
      - "8080:80"

  server:
    build: ./server
    depends_on:
      - postgres
    environment:
      PGHOST: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: mydb
      PGPORT: 5432
    networks:
      - backend
    ports:
      - "5000:5000"

  client:
    build: ./client
    depends_on:
      - server
    networks:
      - backend
    ports:
      - "5173:5173"
    environment:
      VITE_HOST: "0.0.0.0"
    volumes:
      - ./client:/app

volumes:
  pgdata:

networks:
  backend:
    driver: bridge